---
- hosts: localhost
  vars:
    - node_to_run: "right_node"
  roles: 
    - role: check-cobol
      tags: [cobol]
    - role: check-cucumber
      tags: [cucumber]
    - role: check-java
      tags: [java]
    - role: sonar-check
      tags: [sonar]
